### ISSUE TITLE
Swagger API Docs lead to blank screen

### ISSUE THREAD

**Issue by iotemylabs** [linuxserver/budge#12]
When I access [IP]:[PORT]/api/docs/ in 2 different web browsers (Chrome and Chromium based), tab says Swagger UI. but takes me to a complete blank screen.

**Comment by alex-phillips** [comment]
This might be an issue with http vs https. If you're running the docker container, try and map port 443 instead of 80 and hit the IP on https and see if it works then? If that's the case, I'll see if I can put in a workaround for http-only.

**Comment by alex-phillips** [comment]
Closing this, please let me know if you're still encountering this issue with my above suggestion.
