### ISSUE TITLE
API Does not return budget ID

### ISSUE THREAD

**Issue by iotemylabs** [linuxserver/budge#16]
When running This command:
`curl -k -X GET "https://[IP]:6443/api/budgets" -H  "accept: application/json" -H "Authorization: Bearer <key>"`

It gives me this error:
`{"message":"Something went wrong!"}`

No other endpoints are available, as well, even when adding the Auth Header at the /login endpoint.

**Comment by alex-phillips** [comment]
The autorization header does not need the `Bearer ` prefix on the value. Remove that and see if you can successfully get responses.
