### ISSUE TITLE
Feature idea: Select currency

### ISSUE THREAD

**Issue by spiffzilla** [linuxserver/budge#2]
It would be neat to be able to change currency so that we who use something that's not $ can have it a little bit more correct.

List of currencies as en axample:
https://www.fao.org/3/bt976e/bt976e.pdf

**Comment by XisoP01** [comment]
+1
would love to see this

**Comment by alex-phillips** [comment]
Thanks for the feature idea! I do plan to support selection of more than one currency in the future. The project is already using dinero.js which has currency support and I have not hard coded any specific currency amounts into the project as this was something I wanted to be sure I was ready to support in the future.

I think it will likely be a setting on the budget item itself, not application-wide, that way you could have multiple budgets in different currencies if desired.

**Comment by sturgeo** [comment]
+1 for other currencies

**Comment by alex-phillips** [comment]
I (believe) I've just about completed multi-currency support. You can view the progress on this branch: https://github.com/linuxserver/BudgE/tree/multi-currency-support

**Comment by alex-phillips** [comment]
This has been merged and included as of v0.0.8
