### ISSUE TITLE
[BUG] Impossible to change email and password in the settings

### ISSUE THREAD

**Issue by mariushosting** [linuxserver/budge#29]
running the docker version, there is impossible to create new account, change email and password.

**Comment by alex-phillips** [comment]
You should be able to create a new account by logging out and then creating a new account at the login screen.

As far as unable to change email / password, I'm unable to reproduce this. Can you share your docker logs to help troubleshoot the issue?

**Comment by mariushosting** [comment]
Hello, 
I can't create any account. It always said email already exist when I click create account. Never insert any email.
![not work](https://user-images.githubusercontent.com/37554361/172242533-fb681622-3bc4-438c-bfb8-f1ca9d413c4b.png)
[_budge_logs.txt](https://github.com/linuxserver/budge/files/8847779/_budge_logs.txt)

**Comment by charles-997** [comment]
To create a new account, _first_ type in your desired user name and password, _then_ create a new account.

I ran into this same scenario.

**Comment by mariushosting** [comment]
> To create a new account, _first_ type in your desired user name and password, _then_ create a new account.
> 
> I ran into this same scenario.

is there any environment variables for this?

**Comment by charles-997** [comment]
I am not aware of a way to set username/password via the docker compose file.
I set it via the GUI and then ensure the storage that is mounted to the container is snapshot-ed & backed up regularly.

**Comment by alex-phillips** [comment]
@mariushosting yes, sorry for the confusion. The login page is also (currently) the registration page. Simply enter your desired email and password and 'create account' will create that account and log you in.
