### ISSUE TITLE
Feature Idea: Adding REST API Support

### ISSUE THREAD

**Issue by iotemylabs** [linuxserver/budge#3]
Adding a REST API by utilizing the Envelopes as Objects, and endpoints to import CSVs, Export CSVs, POST Transactions, and whatnot.

This could also be useful, for maybe down the road, extending it to utilize the Plaid API Like this for Firefly III:

https://gitlab.com/GeorgeHahn/firefly-plaid-connector

**Comment by alex-phillips** [comment]
@iotemylabs Great news! There is already a rest API supported as well as swagger documentation for it. You can access the swagger docs via http://IP_ADDRESS/api/docs/.

When you use the login endpoint, it will return a token item. You can include this token value either in a cookie value named `jwt` OR the `authorization` header.

**Comment by iotemylabs** [comment]
The Swagger API Docs lead me to a blank page
