### ISSUE TITLE
Swagger Docs

### ISSUE THREAD

**Issue by acolombo11** [linuxserver/BudgE#34]
Hey!

I'd like to build a mobile app using budge as a backend, I've noticed swagger should generate the documentation at /docs, but if I try to access it I can only see the react frontend and cannot access the swagger documentation.

Any tips?

**Comment by alex-phillips** [comment]
@acolombo25 Try accessing it with the path `/api/docs/`. Since it is proxied on the backend, all requests to the API itself (including docs) should have the `/api` prefix.
