### ISSUE TITLE
Allow deleting an account, or change it's balance when there is not yet any transactions

### ISSUE THREAD

**Issue by Extarys** [linuxserver/BudgE#35]
I created my first account, a credit card, and forget to set a negative balance. I can't delete it or change the initial balance. I know the backend logic for deleting an account is not as simple as deleting a single row in the DB though.

It's probably in the same water as https://github.com/linuxserver/budge/issues/1 :)

Posting here so we can keep track when there are developments on that end - or in case I missed an obvious thing :laughing:

**Comment by Extarys** [comment]
Well well, I finally found where the initial transaction was and I can edit the amount by double clicking it.
Ofc I found this after posting the issue :roll_eyes: 


![image](https://user-images.githubusercontent.com/11581433/175183716-85dc2914-9500-41ec-b4eb-067f9292ffa3.png)

**Comment by alex-phillips** [comment]
Glad you found it! If you have any suggestions on making this a bit more intuitive, please let me know.

**Comment by Extarys** [comment]
Well we still need a way to move accounts from/to "Off budget" and eventually a way to remove them :)

> If you have any suggestions on making this a bit more intuitive, please let me know. 

I'll keep that in mind, no idea yet, but maybe adding an option in the account context menu would do the trick, like an account option modal where you set the name, type, initial balance.
