### ISSUE TITLE
Reordering is broken in Safari and Firefox

### ISSUE THREAD

**Issue by jsaltzman** [linuxserver/budge#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When I drag in Firefox, it shows a RED (/) sign (like a no walking sign). When I drag in Safari, it shows an image of the sidebar. I am attaching this image.

Further, I am unable to drag accounts up, only down. So if I want #2 to be number one, I cannot drag 2 to 1, I need to drag 1 to 2.
------------------------------

## Expected Behavior

Ideally, dragging should let us hold the line item that we are dragging so we can see where we are re arranging it too.

User should be able to drag up and down.

## Current Behavior

Odd behavior and weird images when dragging

## Steps to Reproduce

1. Drag accounts to reorder in sidebar menu

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Docker logs

(Previously had a screenshot here but would prefer not to share due to sensitive financial info.

**Comment by alex-phillips** [comment]
I believe this is now resolved with 0.0.4. Going to close this, but feel free to let me know if you are still having reordering issues.
