### ISSUE TITLE
Credit Card does not appear in budget until first transaction

### ISSUE THREAD

**Issue by jsaltzman** [linuxserver/budge#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After adding a credit card with a current balance, it should show in the budget so I can allocate funds to it.

## Current Behavior
Instead it does not appear until you make a transaction on that card. Even if it has a balance.

## Steps to Reproduce

1. Add a credit card
2. Set its balance

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

Installed on unraid using the App Store.

**Comment by alex-phillips** [comment]
Thanks for the bug report! Just pushed a fix for this here: https://github.com/linuxserver/budge/commit/235aa0e98b18e17147cbc1992ff6aa7dc8af7994
